version: '3'
name: deepkit-starter

services:
  edgedb:
    image: edgedb/edgedb:2.9
    restart: unless-stopped
    volumes:
      - ./edgedb-cli-config:/root/.config/edgedb
      - ../edgedb.toml:/edgedb.toml:ro
      - ../dbschema:/dbschema
      - ~/dev/docker-volumes/deepkit-starter/edgedb:/var/lib/edgedb/data
    ports:
      - 15656:5656
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_DATABASE: deepkit_starter
      EDGEDB_SERVER_USER: deepkit_starter
      EDGEDB_SERVER_PASSWORD: password
      EDGEDB_SERVER_ADMIN_UI: enabled
